package org.flossware.agent.domain.event;

public enum EventType {
    SESSION_STARTED, SESSION_SUSPENDED, SESSION_RESUMED, SESSION_CLOSED,
    INTERACTION_STARTED, INTERACTION_COMPLETED, INTERACTION_FAILED,
    MEMORY_CREATED, TASK_STARTED, TASK_COMPLETED, TASK_FAILED, TOOL_INVOKED, ARTIFACT_CREATED
}
